// Generated by 'unplugin-auto-import'
export {}
declare global {
  const computed: typeof import('@vue/runtime-dom')['computed']
  const defineComponent: typeof import('@vue/runtime-dom')['defineComponent']
  const inject: typeof import('@vue/runtime-dom')['inject']
  const onMounted: typeof import('@vue/runtime-dom')['onMounted']
  const onUpdated: typeof import('@vue/runtime-dom')['onUpdated']
  const provide: typeof import('@vue/runtime-dom')['provide']
  const reactive: typeof import('@vue/runtime-dom')['reactive']
  const ref: typeof import('@vue/runtime-dom')['ref']
  const toRef: typeof import('@vue/runtime-dom')['toRef']
  const toRefs: typeof import('@vue/runtime-dom')['toRefs']
  const watch: typeof import('@vue/runtime-dom')['watch']
  const watchEffect: typeof import('@vue/runtime-dom')['watchEffect']
}
