// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    DefaultPage: typeof import('./src/components/DefaultPage.vue')['default']
    DropZone: typeof import('./src/components/DropZone.vue')['default']
    Dummy: typeof import('./src/components/Dummy.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFile: typeof import('./src/components/UploadFile.vue')['default']
  }
}
